download:
  test1:
    - https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-zip-file.zip
  test2:
    - https://www.learningcontainer.com/wp-content/uploads/2020/05/sample.tar
    - https://getsamplefiles.com/download/rar/sample-4.rar
  test3:
    - https://getsamplefiles.com/download/gzip/sample-2.gz
    - https://getsamplefiles.com/download/tar/sample-4.tar
    - https://getsamplefiles.com/download/tar/sample-1.tar
    - https://getsamplefiles.com/download/7z/sample-3.7z
